# This is a config for E2B sandbox template.
# You can use template ID (hg02z8aexvw928qvuq87) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("hg02z8aexvw928qvuq87") # Sync sandbox
# sandbox = await AsyncSandbox.create("hg02z8aexvw928qvuq87") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('hg02z8aexvw928qvuq87')

team_id = "7871d1e6-c03b-4dcf-b3f8-78c5b2609fe0"
memory_mb = 4_098
cpu_count = 2
dockerfile = "e2b/e2b.Dockerfile"
template_id = "hg02z8aexvw928qvuq87"
